### ISSUE TITLE
Ignores script parameter default value

### ISSUE THREAD

**Issue by kraai** [IISResetMe/PSProfiler#18]
When I add the following code to `foo.ps1` and run `foo.ps1`, it prints "foo".  If I run `Measure-Script -Path foo.ps1`, it outputs nothing.

```powershell
param(
    [string]$Foo = 'foo'
)

$Foo
```

I expect it to output the same thing in both cases.  Is this the intended behavior?

**Comment by IISResetMe** [comment]
Thank you for your interest and feedback related to PSProfiler @kraai, and apologies for my late response!

> Is this the intended behavior?

It is indeed! `Measure-Script` is designed to closely mirror the `Measure-Command` cmdlet, so as to act as a drop-in replacement.

This means we instrument and execute the code, swallow the output, and the return information about the time it took to execute instead of regular output. 

You can still observe side-effects of your code being executed:

```
Measure-Script {
param(
    [string]$Foo = 'foo'
)

Write-Host $Foo  # Write-Host bypasses the default output stream
}
```

Or you can use the `-ExecutionResultVariable` parameter to collect the regular output to a local variable at the call site:

```
PS ~> Measure-Script { ... } -ExecutionResultVariable myResult
PS ~> $myResult
foo
```
